@Backend_HostAddress = https://localhost:7003/api


// Get all lists
Get {{Backend_HostAddress}}/List

###

// Get one list by id (2)
GET {{Backend_HostAddress}}/List/2

###

// Get one list by id - NotFound()
GET {{Backend_HostAddress}}/List/200

###

// Add new list
Post {{Backend_HostAddress}}/List
Content-Type: application/json

"test_test"

###

// Update list's name
Patch {{Backend_HostAddress}}/List/7
Content-Type: application/json

"test_test_test_test x4"

###

// Delete list by id
delete {{Backend_HostAddress}}/List/7

###



// Get memorynote by id
GET {{Backend_HostAddress}}/MemoryNote/12

###

// Get list of memorynotes for list id
GET {{Backend_HostAddress}}/MemoryNote/List/1

###

// Create new memorynote
POST {{Backend_HostAddress}}/MemoryNote
Content-Type: application/json

{
    "name":"test2",
    "description":"test2",
    "priority":"2",
    "listId":"1"
}

###

// Update memorynote
PATCH {{Backend_HostAddress}}/MemoryNote/12
Content-Type: application/json

{
    "name":"test3",
    "description":"test3",
    "priority":"3"
}

###

// Delete memorynote
DELETE {{Backend_HostAddress}}/MemoryNote/16